UPDATE `settings` SET `id`='SETTINGS:ACCOUNT:OWNER:USERNAME' WHERE `id`='SETTINGS:ACCOUNT:ADMIN:USERNAME';
UPDATE `settings` SET `id`='SETTINGS:ACCOUNT:OWNER:PASSWORD' WHERE `id`='SETTINGS:ACCOUNT:ADMIN:PASSWORD';
UPDATE `settings` SET `id`='SETTINGS:ACCOUNT:OWNER:LOG_PASSWORD' WHERE `id`='SETTINGS:ACCOUNT:ADMIN:LOG_PASSWORD';