UPDATE `settings` SET `id`='BACKGROUNDSERVICES:DIRECTORY_SCANNER:SCHEDULE' WHERE `id`='BACKGROUNDSERVICES:SCHEDULES:DIRECTORY_SCANNER';
UPDATE `settings` SET `id`='BACKGROUNDSERVICES:EMAIL_REPORT:SCHEDULE' WHERE `id`='BACKGROUNDSERVICES:SCHEDULES:EMAIL_REPORT';
UPDATE `settings` SET `id`='BACKGROUNDSERVICES:CLEANUP:SCHEDULE' WHERE `id`='BACKGROUNDSERVICES:SCHEDULES:CLEANUP';

DELETE FROM `settings` WHERE `id`='BACKGROUNDSERVICES:DIRECTORY_SCANNER:ENABLED';
DELETE FROM `settings` WHERE `id`='BACKGROUNDSERVICES:EMAIL_REPORT:ENABLED';
DELETE FROM `settings` WHERE `id`='BACKGROUNDSERVICES:CLEANUP:ENABLED';

INSERT INTO `settings` ('id', 'value') VALUES ('BACKGROUNDSERVICES:DIRECTORY_SCANNER:ENABLED', 'True');
INSERT INTO `settings` ('id', 'value') VALUES ('BACKGROUNDSERVICES:EMAIL_REPORT:ENABLED', 'True');
INSERT INTO `settings` ('id', 'value') VALUES ('BACKGROUNDSERVICES:CLEANUP:ENABLED', 'True');